{% extends "includes/base.phtml" %}

{% block title %}Restauranteur{% endblock %}

{% block content %}
<h1>Restauranteur</h1>

<ul>
{% for menu in menus %}
	<li>
		{{ menu.title }}

		<ul>
		{% for product in menu.products %}
			<li>{{ product.title }} - {{ product.price|format_currency('GBP') }}</li>
		{% endfor %}
		</ul>

		<a href="/menu/{{ menu.id }}/product/add">Add a product</a>
	</li>
{% endfor %}
</ul>

<a href="/menu/add">Add a new menu</a>
{% endblock %}