{% extends "includes/base.phtml" %}

{% block title %}Add menu | Restauranteur{% endblock %}

{% block content %}
<h1>Add a menu</h1>

<form method="post" class="flow column justify-centre vertical-centre">
	<input type="hidden" name="menu_id" value="{{ menu_id }}" />

	<label for="title">Product title:</label>
	<input type="text" name="title" id="title" />

	<label for="price">Price:</label>
	<input type="number" name="price" id="price" step=".01" min="0" />

	<button>Add product</button>
</form>
{% endblock %}